version: '3'

services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
            - '8081:8081'
        depends_on:
            - client_server
            - api_server
        restart: always
    client_server:
        build:
            context: ./client
            dockerfile: Dockerfile
        # ports:
            # - '8082:3000'
        # restart: always
    api_server:
        build:
            context: ./server
            dockerfile: Dockerfile
        
        volumes:
            - './server:/server'
        # ports:
            # - '8083:3000'
        # restart: always